export const LOGINREQUEST = 'LOGINREQUEST';
export const LOGINSUCCESS = 'LOGINSUCCESS';
export const LOGINERROR = 'LOGINERROR';

export const REGISTERREQUEST = 'REGISTERREQUEST';
export const REGISTERSUCCESS = 'REGISTERSUCCESS';
export const REGISTERERROR = 'REGISTERERROR';

export const ALLUSERDATAREQUEST = 'ALLUSERDATAREQUEST';
export const ALLUSERDATASUCCESS = 'ALLUSERDATASUCCESS';
export const ALLUSERDATAFAILURE = 'ALLUSERDATAFAILURE';

export const UPDATEUSERREQUEST = 'UPDATEUSERREQUEST';
export const UPDATEUSERSUCCESS = 'UPDATEUSERSUCCESS';
export const UPDATEUSERFAILURE = 'UPDATEUSERFAILURE';

export const DELETEUSERREQUEST = 'DELETEUSERREQUEST';
export const DELETEUSERSUCCESS = 'DELETEUSERSUCCESS';
export const DELETEUSERFAILURE = 'DELETEUSERFAILURE';

export const GETSINGLEUSERREQUEST = 'GETSINGLEUSERREQUEST';
export const GETSINGLEUSERSUCCESS = 'GETSINGLEUSERSUCCESS';
export const GETSINGLEUSERFAILURE = 'GETSINGLEUSERFAILURE';

export const LOGOUT = 'LOGOUT';
